# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra'
    backendServiceArm: 'shivansh'
    backendAzureRmOverrideSubscriptionID: '3bafb5d4-689a-4313-b617-9f3367263cd7'
    backendAzureRmResourceGroupName: 'rgg1'
    backendAzureRmStorageAccountName: 'stgg1'
    backendAzureRmContainerName: 'mycontainer'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra'
    environmentServiceNameAzureRM: 'shivansh'
    environmentAzureRmOverrideSubscriptionID: '3bafb5d4-689a-4313-b617-9f3367263cd7'
